openapi: 3.0.3
info:
  title: Integrazione B2B Appalti- Fascicolo Virtuale - OpenAPI 3.0
  x-summary: >-
    Questo servizio ritorna la data e l'ora attuali in UTC.
  description: |-
   Vengono descritti i servizi B2B richiamati per l'accesso al Facicolo Virtuale dell'Operatore Economico da parte della Stazione Appaltante. 
   https://yakworks.github.io/gorm-rest-api/design-principles/schema/
      #### Documentazione
    Il servizio Ora esatta ritorna l'ora del server in formato RFC5424 (syslog).

    `2018-12-30T12:23:32Z`

    Qui va' inserita la documentazione principale del servizio.
    Il testo dev'essere diviso in piu' parti, tutte scritte in Markdown.

    Le Api sono utilizzati per l'intergrazione B2B con i Sistemi Appaltanti per le fasi di Definizione e Pubblicazione Appalto, Aggiudicazione Appalto e Esecuzione Contratto dell'Appalto.
    Il Servizio Appaltante deve chiamare nella sequenza e nella modalità descritte in dettaglio nella documentazione fornita.

    
    
    #### Note

    Il servizio non richiede autenticazione, ma va' usato rispettando gli
    header di throttling esposti in conformita' alle Linee Guida del Modello di interoperabilita'.

    Usa questa sezione per annotazioni specifiche, riferimenti normativi e/o
    per manleve ed esclusioni di responsabilita' eventualmente non incluse in -termsOfService`.

    #### Informazioni tecniche ed esempi

    Esempio:

    ```
    http://localhost:8443/datetime/v1/echo
    {
      'datetime': '2018-12-30T12:23:32Z'
    }
    ```

    Qui e' possibile introdurre brevi informazioni tecniche ed esempi.
  # I termini del servizio contengono un riferimento
  #   a tutte le indicazioni e le note legali per l'utilizzo
  #   del servizio, inclusi gli eventuali riferimenti utili al GDPR.
  termsOfService: 'http://swagger.io/terms/'
  # Chi posso contattare per informazioni sul servizio e sul suo stato?
  contact:
    email: mario.rossi@anticorruzione.it
    name: Mario Rossi
    url: https://twitter.com/ioggstream
  # L'audience delle API. Attualmente e' definito solamente
  #   la tipologia `public`.
  x-audience:
    - public
  # Ogni API deve avere un UUID, invariante nel tempo e
  #   rispetto al `title`.
  x-api-id: 00000000-0000-0000-0000-000000000000
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  # Per dare indicazioni sul ciclo di vita dell'API
  # si puo' usare un parametro come:
  x-lifecycle:
    published: 1970-01-01
    deprecated: 2050-01-01
    retired: 2050-06-01
    maturity: published  
  version: 1.0.0
servers:
  - url: https://repositorydocument.swagger.io/api/v1
    description: Development server
tags:
  - name: SA
    description: Operazioni invocate dalla SA
  - name: OE
    description: Operazioni invocate dall'OE
  - name: serviziTecnici 
    description: Operazioni richiesti dalle linee guida sull'interoperabilità   
paths:
  /status:
    get:
      summary: Ritorna lo stato dell'applicazione. SINCRONO
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: idStatusShow
      tags:
        - serviziTecnici
      responses:
        '200':
            description: |
              Il server ha ritornato lo status. In caso di problemi
              ritorna sempre un problem+json.
              # Questi header di throttling sono obbligatori e definiti
              # nel Nuovo modello di interoperabilità.
            headers: &ratelimit_headers 
              X-RateLimit-Limit:
                 $ref: '#/components/headers/X-RateLimit-Limit'
              X-RateLimit-Remaining:
                 $ref: '#/components/headers/X-RateLimit-Remaining'
              X-RateLimit-Reset:
                 $ref: '#/components/headers/X-RateLimit-Reset'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/BaseResponse'
        '429':
            description: Limite di richieste raggiunto
            headers:
              Retry-After:
                $ref: '#/components/headers/Retry-After'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/BaseResponse'        
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BaseResponse'          
  /richiesta-accesso-fvoe:
    post:
      tags:
         - SA
      summary: API Rest per la creazione della richiesta di accesso al FVOE. ASINCRONO 
      description: Inserimento della richiesta di accesso ai documenti presenti nel FVOE. ASINCRONO 
      operationId: idAccessoRichiestaFVOE
      requestBody:
        description: Inserimento Richiesta di Accesso
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RichiestaAccessoRequest'
        required: true
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito l'idRichiesta generato da ANAC
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichiestaAccessoResponse'
          links:
            StatoRichiestaAccessoIdLink:  
              operationId: idRichiestaAccessoFVOEVerifica
              parameters:
                idRichiesta: '$response.body#/idRichiesta'
              description: >
                Il valore di `idRichiesta` restituito nella riposta può essere usato per richiamare `GET /verifica-richiesta-accesso`.  
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - write:NPA
  /verifica-richiesta-accesso-fvoe:
    get:
      tags:
        - SA
      summary: API Rest per verificare l'esito della richiesta di accesso. SINCRONO
      description: API Rest per il recupero dell'esito della richiesta di accesso. SINCRONO
      operationId: idRichiestaAccessoFVOEVerifica
      parameters:
        - in: query
          name: idRichiesta
          description: identificativo univoco della Richiesta di accesso definito da ANAC. (A UUID specified by RFC4122)
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatoRichiestaResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - write:NPA
  /autorizza-accesso-fvoe:
    post:
      tags:
         - OE
      summary: API Rest per la conferma di accesso al FVOE. SINCRONO 
      description: Il servizio permette all'OE di autorizzare l'accesso al FVOE da parte della SA. SINCRONO 
      operationId: idAccessoAutorizza
      requestBody:
        description: Inserimento Appalto con tutti i dati aggiuntivi
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutorizzaAccessoRequest'
        required: true
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito l'idAppalto generato da ANAC
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutorizzaAccessoResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - write:NPA
  /ricerca-documenti-fvoe:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per la ricerca dei documenti di un FVOE. SINCRONO
      description: viene recuperata la lista con i dati di sintesi dei documenti. SINCRONO
      operationId: idDocumentiRicerca
      parameters:
        - in: query
          name: dataCreazioneDa
          description: Data di creazione dell'Documento con intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataCreazioneA
          description: Data di creazione dell'Documento con intervallo precedente (A datetime specified by RF3339) 
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query  
          name: stato  
          description: stato del documento
          schema:
            $ref: '#/components/schemas/StatoDocumentoEnum'
        - in: query  
          name: tipo  
          description: tipo del documento
          schema:
            $ref: '#/components/schemas/TipoDocumentoEnum'            
        - in: query
          name: page
          description: numero di pagine da visualizzare
          schema:
            type: integer
            format: int32
        - in: query  
          name: perPage
          description: numero di elementi per pagina
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentiListaResponse'
          links:
            RecuperaDocumentoIdLink:  
              operationId: idDocumentoDettaglio
              parameters:
                idDocumento: '$response.body#/result.idDocumento'
              description: >
                Il valore di `idDocumento` restituito nella riposta può essere usato per richiamare `GET /recupera-documento`.        
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA                
  /recupera-documento-fvoe:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per il recupero del documento dal FVOE. SINCRONO
      description: Viene resituita il Documento (Metadati e Binario). SINCRONO
      operationId: idDocumentoDettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito il Documento
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecuperaDocumentoResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'       
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA  
  /richiedi-documento:
    get:
      tags:
        - SA
      summary: API Rest per la richiesta del documento agli enti certificatori. ASINCRONO - ASIMMETRICO
      description: viene richiesta la produzione di un nuovo documento agli enti certificatori.
         ASINCRONO - ASIMMETRICO
      operationId: idDocumentoRichiedi
      parameters:
        - in: query
          name: idFascicolo
          description: identificativo univoco del FVOE.
          required: true
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: tipoDocumento
          description: tipologia del documento da richiedere.
          required: true
          schema:
            $ref: '#/components/schemas/TipoDocumentoEnum'
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RichiediDocumentoResponse'
          links:
            RecuperaDocumentoIdLink:  
              operationId: idDocumentoDettaglio
              parameters:
                idDocumento: '$response.body#/result.idDocumento'
              description: >
                Il valore di `idDocumento` restituito nella riposta può essere usato per richiamare `GET /recupera-documento`.  
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA  
  /recupera-storico-documento-fvoe:
    get:
      tags:
        - SA
      summary: API Rest per il recupero dello storico di un documento del FVOE. SINCRONO
      description: viene resituito il dettaglio dello storico di un documento del FVOE.
      operationId: idStoricoDocumentoDettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaStoricoResponse'   
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA          
  /ricerca-documenti-fva:
    get:
      tags:
        -  SA
      summary: API Rest per la ricerca dei documenti di un FVA. SINCRONO
      description: viene recuperata la lista con i dati di sintesi dei documenti. SINCRONO
      operationId: idDocumentiFVARicerca
      parameters:
        - in: query
          name: codiceAppalto
          description: il codice dell'Appalto         
          schema:
            type: integer
            format: int32
        - in: query    
          name: idAppalto
          description: Identificativo univoco dell'Appalto definito da ANAC. Restituito dall'operazione di creazione Appalto. (A UUID specified by FC4122).
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"  
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC
          schema:
            type: string
            example: 9050626CD6
        - in: query
          name: dataCreazioneDa
          description: Data di crezione del documento con intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataCreazioneA
          description: Data di crezione del documento con intervallo precedente (A datetime specified by RF3339) 
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query
          name: page
          description: numero di pagine da visualizzare
          schema:
            type: integer
            format: int32
        - in: query  
          name: perPage
          description: numero di elementi per pagina
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentiListaResponse'          
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA                
  /recupera-documento-fva:
    get:
      tags:
         - SA
      summary: API Rest per il recupero del documento dal FVA. SINCRONO
      description: Viene resituita il Documento (Metadati e Binario). SINCRONO
      operationId: idDocumentoFVADettaglio
      parameters:
        - in: query
          name: idDocumento
          description: Identificato del Documento generato da ANAC
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: idAppalto
          description: Id dell'Appalto, alternativo al CIG
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC, alternativo all'idAppalto
          schema:
            type: string
            example: 9050626CD6
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito l'oggetto Piano
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecuperaDocumentoResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'       
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA  
  /recupera-storico-documento-fva:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per il recupero dello storico di un documento del FVA. SINCRONO
      description: viene resituito il dettaglio dello storico di un documento del FVA.
      operationId: idStoricoDocumentoFVADettaglio
      parameters:
        - in: query
          name: idAvviso
          description: Identificativo dell'Avviso generato da ANAC.
          required: true
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaStoricoResponse'   
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA          
  /ricerca-fascicoli-fva:
    get:
      tags:
        -  SA
      summary: API Rest per la ricerca dei fascicoli degli appalti. SINCRONO
      description: viene recuperata la lista con i dati di sintesi dei FVA. SINCRONO
      operationId: idFascicoliRicerca
      parameters:
        - in: query
          name: codiceAppalto
          description: il codice dell'Appalto         
          schema:
            type: integer
            format: int32
        - in: query    
          name: idAppalto
          description: Identificativo univoco dell'Appalto definito da ANAC. Restituito dall'operazione di creazione Appalto. (A UUID specified by FC4122).
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"  
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC
          schema:
            type: string
            example: 9050626CD6
        - in: query
          name: dataCreazioneDa
          description: Data di crezione dell'Appalto con intervallo successivo (A datetime specified by RF3339)
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'
        - in: query
          name: dataCreazioneA
          description: Data di crezione dell'Appalto con intervallo precedente (A datetime specified by RF3339) 
          schema:
            type: string
            format: datetime
          example: '2015-05-28T14:07:17Z'  
        - in: query
          name: page
          description: numero di pagine da visualizzare
          schema:
            type: integer
            format: int32
        - in: query  
          name: perPage
          description: numero di elementi per pagina
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentiListaResponse'          
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA                
  /recupera-fascicolo-fva:
    get:
      tags:
         - SA
      summary: API Rest per la consultazione delle informazioni di dettaglio di un FVA. SINCRONO
      description: vengono restituite le informazioni di dettaglio di un FVA. SINCRONO
      operationId: idFascicoloDettaglio
      parameters:
        - in: query
          name: idAppalto
          description: Id dell'Appalto, alternativo al CIG
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: CIG
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC, alternativo all'idAppalto
          schema:
            type: string
            example: 9050626CD6
      responses:
        '200':
          description: Operazione terminato con successo. Viene restituito l'oggetto Piano
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecuperaFascicoloResponse'
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'       
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA  
  /recupera-storico-fascicolo-fva:
    get:
      tags:
        - SA
      summary: API Rest per il recupero dello storico di un FVA. SINCRONO
      description: viene resituito il dettaglio dello storico di FVA.
      operationId: idStoricoFascicoloFVADettaglio
      parameters:
        - in: query
          name: idAvviso
          description: Identificativo dell'Avviso generato da ANAC.
          required: true
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaStoricoResponse'   
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - read:NPA          
  /recupero-anagrafica-oe:
    get:
      tags:
        - SA
        - OE
      summary: API Rest per il recupero dell’anagrafica degli OE. SINCRONO
      description: vengono restituito i dati anagrafici dell'OE. SINCRONO
      operationId: idAnagraficaOERicerca
      parameters:
        - in: query    
          name: codiceFiscale
          description: Codice Fiscale OE.
          required: true
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"  
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaAnagraficaOEResponse'          
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
            $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
        - applicationDB_auth:
            - write:FVA
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    Sunset:
      description: The Sunset HTTP response header field, indicates that a URI is likely
        to become unresponsive at a specified point in the future.  It also defines
        a sunset link relation type that allows linking to resources providing information
        about an upcoming resource or service sunset.
      schema:
        example: Sun, 06 Nov 1994 08:49:37 GMT
        externalDocs:
          url: https://tools.ietf.org/html/rfc7231#appendix-D
        format: HTTP-date
        maxLength: 30
        type: string
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer  
    X-Ratelimit-Used: 
      description: The number of requests used in the current period
      schema:
        type: integer
        format: int32      
  responses:
    200AckResponse:
      description: Richiesta accettata
      headers: *ratelimit_headers
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AckResponse'
    400BadRequest:
      description: Richiesta malformattata
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    404NotFound:
      description: Dato non trovato
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    429TooManyRequests:
      description: Limite di richieste raggiunto
      headers:
        Retry-After:
            $ref: '#/components/headers/Retry-After'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    500InternalServerError:
      description: Errore generico. Operazione terminato con errore. Viene restitutito il dettaglio dell'errore
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    503ServiceUnavailable:
      description: Service Unavailable
      headers:
        Retry-After:
            $ref: '#/components/headers/Retry-After'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    default:
      description: |-
       Errore inatteso. Non ritornare informazioni
       sulla logica interna e/o non pertinenti all'interfaccia.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    StatoAutorizzazioneEnum:
      description: lo stato in cui si può trovare il lotto
      type: string
      minimum: 1
      enum: ['IN LAVORAZIONE', 'CONFERMATO', 'CANCELLATO', 'IN ATTESA DI PUBBLICAZIONE','IN PUBBLICAZIONE FERMATA','PUBBLICATO','NON AGGIUDICATO', 'AGGIUDICATO', 'IN SOTTOSCRIZIONE CONTRATTO','IN ESECUZIONE','ANNULLATO','SOSPESO', 'CONCLUSO','COLLAUDATO']
    StatoDocumentoEnum:
      description: lo stato in cui si può trovare il lotto
      type: string
      minimum: 1
      enum: ['IN LAVORAZIONE', 'CONFERMATO', 'CANCELLATO', 'IN ATTESA DI PUBBLICAZIONE','IN PUBBLICAZIONE FERMATA','PUBBLICATO','NON AGGIUDICATO', 'AGGIUDICATO', 'IN SOTTOSCRIZIONE CONTRATTO','IN ESECUZIONE','ANNULLATO','SOSPESO', 'CONCLUSO','COLLAUDATO']
    StatoRichiestaType:
        type: string
        minimum: 1
        enum: ['IN LAVORAZIONE', 'CREATA', 'CONFERMATA', 'CANCELLATA']   
        description: >
          stato- Stato in cui si trova la Scheda:
           * 'IN LAVORAZIONE' - Stato iniziale della scheda
           * 'CONFERMATA' - I dati della scheda sono confermati
           * 'CANCELLATA' - i dati della scheda sono annullati
    StatoLottoEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/YAML/main/anticorruzione-npa-fvoe/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/StatoLottoEnum'
    TipoDocumentoEnum: 
      type: string
      minimum: 1
      enum: ['DURC', 'VISURA_CAMERALE', 'ETC..'] 
      description: >
        tipo oocumento- Tipo Documento:
         * 'DURC' - Visura Camerale, Casellario informatico, Certificazione disabili, Agenzie delle Entrate, * Attestazione S.O.A., Fatture verso PA, Buon esito lavori, Bilancio, Documenti a comprova Requisiti Fatturato, Documenti a comprova requisiti tecnici, Certificato antimafia, Elenco principali servizi / forniture, Certificazione ISO, Certificazione Prodotti, Attestazioni titoli di studio e * professionali, etc.)
         * 'VISURA_CAMERALE' - 
         * 'ETC..' -
      example: "IN LAVORAZIONE" 
    AppaltoType :
      description: Oggetto che riporta i dati dell'Appalto
      type: object
      additionalProperties: false
      properties:
        idAppalto:
          description: identificativo univoco dell'appalto generato da ANAC
          type: string
          example: xcdsd5#3346
    LottoTypeNew :
      $ref: 'https://raw.githubusercontent.com/domaltomare/YAML/main/anticorruzione-npa-fvoe/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/LottoType'
    LottoType:
      description: Oggetto che riporta tutti i dati del lotto
      type: object
      additionalProperties: false
      properties:
        CIG:
          description: codice identificativo lotto
          type: string
          example: '9050626CD6'
        oggetto:
          description: descrizione del lotto
          type: string
          example: 'Servizio di assistenza e supporto specialistico per rilievo aereo ed elaborazione dati'
        stato:
          $ref: '#/components/schemas/StatoLottoEnum'
        appalto:
          $ref: '#/components/schemas/AppaltoType' 
       # avvisi: 
       #   type: array
      #    items:
      #      $ref: 'https://raw.githubusercontent.com/domaltomare/YAML/main/anticorruzione-npa-fvoe/docs/modello-dati/modello-dati-npa.yaml#/components/schema/AvvisoType'
    FascicoloType: 
      description: Oggetto che riporta i dati del Fascicolo generico
      type: object
      additionalProperties: false
      properties:
        idFascicolo:
          description: identificativo univoco del Fascicolo
          type: string
          example: xcdsd5#3346
    FVOEType:
      allOf: # estende lo schema dati di FascicoloType
        - $ref: '#/components/schemas/FascicoloType'
      description: Oggetto che riporta i dati del FVOE
      type: object
      additionalProperties: false
      properties:
        anagraficaOE: 
          $ref: '#/components/schemas/AnagraficaOEType'
    FVAType:
      allOf: # estende lo schema dati di FascicoloType
        - $ref: '#/components/schemas/FascicoloType'
      description: Oggetto che riporta i dati del FVA
      type: object
      additionalProperties: false
      properties:
        appalto: 
          $ref: '#/components/schemas/AppaltoType'      
    DocumentoType:
      description: Oggetto che riporta i dati del Documento
      type: object
      additionalProperties: false
      properties:
        idDocument:
          description: identificativo univoco del documento
          type: string
          example: xcdsd5#3346
        tipoDcumento:
          $ref: '#/components/schemas/TipoDocumentoEnum'
        statoDocumento:
          $ref: '#/components/schemas/StatoDocumentoEnum'
        fascicoloOE:
            $ref: '#/components/schemas/FVOEType'
        fascicoliA:
          type: array
          items:
            $ref: '#/components/schemas/FVAType'
    ContentDocumentType:
      description: Oggetto che riporta tutti i dati della Pianificazione
      type: object
      additionalProperties: false
      properties:
        estensione:
          description: estensione file
          type: string
          example: "PDF"
        size:
          description: grandezza del documento
          type: string
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        content:
          description: Contenuto in formato Binario del documento
          type: string
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
    AutorizzazioneAccessoType:
      description: Oggetto che riporta tutti i dati della Pianificazione
      type: object
      additionalProperties: false
      properties:
        idRichiesta:
            description: identificativo univoco della richiesta restituito da ANAC in fase di creazione Richiesta
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        dataCreazione:
          description: data creazione della richiesta (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        stato:
          $ref: '#/components/schemas/StatoAutorizzazioneEnum'
        motivo:
          type: string
        dataScadenza:
          description: data limite in cui la richiesta é valida per essere autorizzata(A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'
        richiestaAccesso :
          $ref: '#/components/schemas/RichiestaAccessoType'  
    RichiestaAccessoType:
      description: Oggetto che riporta i dato della Richiesta di Accesso
      type: object
      additionalProperties: false
      properties:
        idRichiesta:
            description: identificativo univoco della richiesta restituito da ANAC.
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        dataCreazione:
          description: data creazione della richiesta (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        dataScadenza:
          description: data limite in cui la richiesta é valida per essere autorizzata(A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'
        anagraficaOE: 
          $ref: '#/components/schemas/AnagraficaOEType' 
        lottoType:
          $ref: '#/components/schemas/LottoType' 
        richiedente : 
          $ref: '#/components/schemas/AnagraficaSAType'
        autorizzazione :
          $ref: '#/components/schemas/AutorizzazioneAccessoType'
    RichiestaAccessoRequest:
      allOf: # estende il modello dati RichiestaAccessoType
        - $ref: '#/components/schemas/RichiestaAccessoType'
      example:
        dataCreazione: "2022-01-23T12:02:05Z"
        dataScadenza: "2022-01-23T12:02:05Z"
        anagraficaOE:
            codice: "UI78588658"
        lottoType:
          CIG: "ACD4546346A"
    AutorizzaAccessoRequest:
      allOf: # estende il modello dati AutorizzaAccessoType
        - $ref: '#/components/schemas/AutorizzazioneAccessoType' 
      example:
        stato: "AUTORIZZATO"
        dataScadenza: "2022-01-23T12:02:05Z"
        richiestaAccesso: 
          idRichiesta: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
    TipoSchedaEnum :
      type: string
      minimum: 1
      enum: ['ELENCO_PARTECIPANTI', 'AGGIUDICAZIONE' , 'AVVIO_CONTRATTO','AVANZAMENTO_CONTRATTO','CONCLUSIONE_CONTRATTO', 'COLLAUDO_CONTRATTO','SOSPENSIONE','RIPRESA_ESECUZIONE_CONTRATTO','RISOLUZIONE CONTRATTO', 'MODIFICA_CONTRATTO' ,'SUBAPPALTO','RECESSO' ,'CONTENZIOSO']
      description: >
            stato- Stato in cui si trova la Appalto:
             * 'ELENCO_PARTECIPANTI'
             * 'AGGIUDICAZIONE' 
             * 'AVVIO_CONTRATTO'- Dati relativi alla creazione del Contratto nela fase di ESECUZIONE
             * 'AVANZAMENTO_CONTRATTO'
             * 'CONCLUSIONE_CONTRATTO' 
             * 'COLLAUDO_CONTRATTO' 
             * 'SOSPENSIONE' 
             * 'RIPRESA_ESECUZIONE_CONTRATTO' 
             * 'RISOLUZIONE CONTRATTO' 
             * 'MODIFICA_CONTRATTO' 
             * 'SUBAPPALTO'
             * 'RECESSO' 
             * 'CONTENZIOSO'
    TipoRuoloEnum:
        type: string
        minimum: 1
        enum: ['RUOLO1', 'RUOLO2', 'RUOLO3', 'RUOLO4']          
    AnagraficaType:
      description: Oggetto che riporta tutti i dati dell'Documento
      type: object
      additionalProperties: false
      properties:
        codice:
          description: codice identificativo anagrafica
          type: string
          example: xcdsd5#3346
    AnagraficaOEType:
      allOf: # estende la classe AnagraficaType
        - $ref: '#/components/schemas/AnagraficaType'
      description: Oggetto specifico dell'anagrafica dell'OE
      type: object
      additionalProperties: false
      properties:
        oggetto:
          description: descrizione della gara
          type: string
          example: Fornitura di strumento XX per XX
    RuoloType:
      description: Oggetto specifico dell'anagrafica dell'OE
      type: object
      additionalProperties: false
      properties:
        ruolo:
          $ref: '#/components/schemas/TipoRuoloEnum'
        dataInizio:
          description: Data di inizio  (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'
        dataFine:
          description: Data di fine  (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2023-01-23T12:02:05Z'
    AnagraficaSAType:
      allOf: # estende la classe AnagraficaType
        - $ref: '#/components/schemas/AnagraficaType'
      description: Oggetto specifico dell'anagrafica dell'OE
      type: object
      additionalProperties: false
      properties:
        nome:
          description: descrizione della gara
          type: string
          example: 'MAURO'
        cognome:
          description: descrizione della gara
          type: string
          example: 'VERDI'
        ruoli:  
          type: array
          items:
            $ref: '#/components/schemas/RuoloType'   
    PaginazioneType:
      description: Oggetto per la paginazione dei risultati
      type: object
      additionalProperties: false
      properties:
        totRows: 
          description: Numero totale di record risultante dalla ricerca
          type: integer
          format: int32
        totPages: 
          description: Numero totale di pagine risultanti dalla ricerca
          type: integer
          format: int32      
        currentPage: 
          description: Numero di pagina corrente
          type: integer
          format: int32
        elementPage:
          description: Numero di elementi per pagina
          type: integer
          format: int32
    RichiestaAccessoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      description: Risposta generica servizio
      type: object
      required:
        - idRichiesta
      properties:
        idRichiesta:
          description: Identificativo univoco della richiesta definito da ANAC. (A UUID specified by RFC4122)
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      example:
        detail: "Richiesta acquisita"
        status: 200
        title: "Operazione Effettuata"
        idRichiesta: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"    
    AutorizzaAccessoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      description: Risposta generica servizio
      type: object
      required:
        - idAutorizzazione
      properties:
        idAutorizzazione:
          description: Identificativo univoco dell'autorizzazione definito da ANAC. (A UUID specified by RFC4122)
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
    RecuperaDocumentoResponse :
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:  
        document: 
          $ref: '#/components/schemas/DocumentoType'
        content:
          $ref: '#/components/schemas/ContentDocumentType'
      example:
        status: 200
        title: "Operazione Effettuata"
        document:
          idDocument: "xcdsd5#3346"
          tipoDcumento: "IN LAVORAZIONE"
          statoDocumento: "IN LAVORAZIONE"
          fascicoloOE:
            idFascicolo: "xcdsd5#3346"
        content: 
          estensione: "PDF"
          size: 2313
          content: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
    RecuperaFascicoloResponse :
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        avviso:
          oneOf:
            - $ref: '#/components/schemas/FVOEType'
            - $ref: '#/components/schemas/FVAType'
      example:
        status: 200
        title: "Operazione Effettuata"
        document:
          idDocument: "xcdsd5#3346"
          tipoDcumento: "IN LAVORAZIONE"
          statoDocumento: "IN LAVORAZIONE"
          fascicoloOE:
            idFascicolo: "xcdsd5#3346"
        content: 
          estensione: "PDF"
          size: 2313
          content: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
    ConsultaAnagraficaOEResponse :
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:  
        anagrafica: 
          $ref: '#/components/schemas/AnagraficaOEType'
    RichiediDocumentoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        idRichiesta:
          description: Identificativo univoco della richiesta definito da ANAC. (A UUID specified by RFC4122)
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
      example:
        status: 200
        title: "Richiesta acquisita"
        type: "https://tools.ietf.org/html/rfc7231#section-6.6.4"
        idRichiesta: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
    StatoRichiestaResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        stato:
          $ref: '#/components/schemas/StatoRichiestaType'
    DocumentiListaResponse :
      allOf: # estende la classe BaseResponse e PaginazioneType
        - $ref: '#/components/schemas/BaseResponse'
        - $ref: '#/components/schemas/PaginazioneType'
      description: Oggetto generico di ritorno di una risposta con paginazione
      type: object
      additionalProperties: false
      properties:
        result: 
          description: risposta di una lista di oggetti paginati specifica del servizio SINCRONO
          type: array
          items:
            $ref: '#/components/schemas/DocumentoType'
      example:
        totRows: 2
        totPages: 1
        currentPage: 1
        elementPage": 2
        result: 
          - idDocument: "xcdsd5#3346"
            tipoDcumento: "DURC"
            statoDocumento: "IN LAVORAZIONE"
            fascicoloOE: 
              idFascicolo: "xcdsd5#3346"
          - idDocument: "xcdsd5#3346"
            tipoDcumento: "DURC"
            statoDocumento: "IN LAVORAZIONE"
            fascicoloOE: 
              idFascicolo: "xcdsd5#3346"
    ConsultaStoricoResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        documenti:
          description: Lista documenti
          type: array
          items:
            $ref: '#/components/schemas/DocumentoType'
    BaseResponse:
      type: object
      additionalProperties: false
      properties:
          detail:
              description: |
                A human readable explanation specific to this occurrence of the
                problem.
              maxLength: 4096
              pattern: ^.{0,1024}$
              type: string
              example: 'Request took too long to complete.'
          instance:
              description: |
                An absolute URI that identifies the specific occurrence of the
                problem.
                It may or may not yield further information if dereferenced.
              format: uri
              maxLength: 2048
              type: string
          status:
              description: |
                The HTTP status code generated by the origin server for this
                occurrence
                of the problem.
              exclusiveMaximum: true
              format: int32
              maximum: 600
              minimum: 100
              type: integer
              example: 503
          title:
              description: |
                A short, summary of the problem type. Written in english and
                readable
                for engineers (usually not suited for non technical stakeholders
                and not localized);
              maxLength: 64
              pattern: ^[ -~]{0,64}$
              type: string
              example: 'Service Unavailable'
          type:
              description: |
                An absolute URI that identifies the problem type. When
                dereferenced,
                it SHOULD provide human-readable documentation for the problem
                type
                (e.g., using HTML).
              default: about:blank
              format: uri
              maxLength: 2048
              type: string
              example: 'https://tools.ietf.org/html/rfc7231#section-6.6.4'  
    ErrorResponse:
      allOf: # estende la classe BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
    AckResponse:
      allOf: # estende la classe BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      example:
        status: 200
        title: "Richiesta acquisita"
  securitySchemes:
    applicationDB_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://oauth/authorize 
          tokenUrl: https://oauth/token             
          scopes:
            write:NPA: modifica dati della componente NuovaPiattaformaAppalti
            read:NPA: lettura dati della componente NuovaPiattaformaAppalti
    apiKeyAuth:
      type: apiKey
      name: apiKeyAuth # name of the header, query parameter or cookie
      in: header  # can be "header", "query" or "cookie"          
